import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Navigation/Header";
import Footer from "@/components/Navigation/Footer";
import GlobalScripts from "@/components/Scripts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <GlobalScripts />
      </body>
    </html>
  );
}